export const REQUEST_STARTED = 'REQUEST_STARTED';
export const REQUEST_SUCCEEDED = 'REQUEST_SUCCEEDED';
export const REQUEST_FAILED = 'REQUEST_FAILED';

export const INCREASE_STATUS = 'INCREASE_STATUS';
export const DECREASE_STATUS = 'DECREASE_STATUS';